-- Introduces a Lists layer between DNC Groups and DNC Numbers, mirroring the
-- Contact List pattern (Group → List → Numbers). `source` moves from the
-- group to the list so a single group can contain numbers from multiple
-- sources (manual, import, agent_disposition, campaign_specific).
--
-- Strategy:
--   1. Create dnc_lists table.
--   2. For each existing dnc_group, materialise a 'Default' list inheriting
--      the group's current source.
--   3. Add dnc_list_id to dnc_numbers and backfill it to the matching
--      Default list.
--   4. Swap the uniqueness constraint from (group, phone) to (list, phone),
--      allowing the same phone to live in multiple lists of the same group.
--   5. Drop dnc_groups.source.

CREATE TABLE IF NOT EXISTS dnc_lists (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  dnc_group_id  UUID        NOT NULL REFERENCES dnc_groups(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  source        TEXT        NOT NULL DEFAULT 'manual',
  created_by    UUID        REFERENCES users(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (dnc_group_id, name)
);

CREATE INDEX IF NOT EXISTS idx_dnc_lists_group ON dnc_lists(dnc_group_id);

-- Backfill: one Default list per existing group, inheriting source.
INSERT INTO dnc_lists (dnc_group_id, name, source, created_by)
SELECT dg.id, 'Default', COALESCE(dg.source, 'manual'), dg.created_by
FROM dnc_groups dg
WHERE NOT EXISTS (
  SELECT 1 FROM dnc_lists dl WHERE dl.dnc_group_id = dg.id AND dl.name = 'Default'
);

-- Add list FK to dnc_numbers (nullable during backfill, tightened below).
ALTER TABLE dnc_numbers
  ADD COLUMN IF NOT EXISTS dnc_list_id UUID REFERENCES dnc_lists(id) ON DELETE CASCADE;

-- Assign every existing number to its group's Default list.
UPDATE dnc_numbers dn
SET dnc_list_id = dl.id
FROM dnc_lists dl
WHERE dl.dnc_group_id = dn.dnc_group_id
  AND dl.name = 'Default'
  AND dn.dnc_list_id IS NULL;

-- Enforce NOT NULL now that every row is backfilled. Wrapped in a DO block
-- so the migration is idempotent on reruns.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'dnc_numbers'
      AND column_name = 'dnc_list_id'
      AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE dnc_numbers ALTER COLUMN dnc_list_id SET NOT NULL;
  END IF;
END $$;

-- Swap unique constraint: (group, phone) → (list, phone). The old constraint
-- has the autogenerated name dnc_numbers_dnc_group_id_phone_number_key.
ALTER TABLE dnc_numbers
  DROP CONSTRAINT IF EXISTS dnc_numbers_dnc_group_id_phone_number_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'dnc_numbers_dnc_list_id_phone_number_key'
  ) THEN
    ALTER TABLE dnc_numbers
      ADD CONSTRAINT dnc_numbers_dnc_list_id_phone_number_key
      UNIQUE (dnc_list_id, phone_number);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_dnc_numbers_list ON dnc_numbers(dnc_list_id);

-- Source now lives on dnc_lists. Drop from dnc_groups.
ALTER TABLE dnc_groups DROP COLUMN IF EXISTS source;
